#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d ξ λ σ ς

bspc config border_width         1
bspc config window_gap           4

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# bspc rule -a Gimp desktop='^8' state=floating follow=on
# bspc rule -a Chromium desktop='^2'
# bspc rule -a mplayer2 state=floating
# bspc rule -a Kupfer.py focus=on
# bspc rule -a Screenkey manage=off

kitty bpytop
