#!/bin/bash

start_time=$(date +%s%3N)
norm_dir="$HOME/Scripts/banana-coding-style-checker/vera"

echo "Running norm in $(pwd)"
files=$(find "$(pwd)"      \
    -type f                \
    -not -path "*/.git/*"  \
    -not -path "*/.idea/*" \
    -not -path "bonus/*"   \
    -not -path "tests/*"   \
    -not -path "/*build/*" \
)

echo "Checking $(echo "$files" | wc -w) files"
# shellcheck disable=SC2046
output=$(vera++                           \
    --profile epitech                     \
    --root "$norm_dir"                    \
    -d $(echo "$files" | tr '\n' ' ')     \
)

if [ -z "$output" ]; then
    echo "No issue found :D"
else
    escaped_path=$(pwd | sed 's/\//\\\//g')
    echo "$output" | sed "s/$escaped_path\///g"
    echo "Found $(echo "$output" | grep -c "$") issues"
fi
end_time=$(date +%s%3N)
echo "Ran in $((end_time - start_time))ms"
