on:
  workflow_dispatch:
  push:

jobs:
  update_screenshot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v26
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.GH_SSH_PRIVATE_KEY }}
          known_hosts: $GH_PUB_KEY

      - name: Get screenshot
        run: |
          nix build .\#screenshot-system.passthru.tests.qtile \
            --print-build-logs -v \
            --extra-experimental-features 'nix-command flakes'

      - name: Push in gist
        run: |
          git config --global user.email "115845162+imjohntitor@users.noreply.github.com"
          git config --global user.name "ImJohnTitor"

          cp result/terminal.png screenshot.png

          git add screenshot.png || echo "no changes"
          git commit -m "Update screenshot" || echo "nothing to commit"
          git push origin master
